version: '3.2'
networks:
  redis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24

services:
  redis:
    build:
      context: ./redis-image
      args:
        REDIS_VERSION: $REDIS_VERSION
    image: redis_alpine
    container_name: redis
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 10001:6379
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./log
        target: /log
      - type: bind
        source: ./conf/redis.conf
        target: /etc/redis/redis.conf
    environment:
      - ANNOUNCE_IP=$ANNOUNCE_IP
      - ANNOUNCE_PORT=$ANNOUNCE_PORT
      - ISSLAVE=0
    entrypoint:
      - /bin/bash
      - /usr/src/sh/redis.sh
    networks:
      redis:
        ipv4_address: 172.24.0.2